# Site settings
title: AtollJ Blog
header-img: img/home-bg.jpg
email: taihi098@gmail.com
copyright_name: AtollJ. All rights reserved.
description: "here is atollj's description place"
baseurl: ""
url: "http://taih098.github.io"
twitter_username: "@keyBjay"
github_username:  taihi098
facebook_username:  "kay.bjay.3"
email_username:  taihi098@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
#exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
